gemspec: update version of dependent "gqtp" gem
Because:
gqtp 1.0.3 doesn't pass below tests.

E
===============================================================================
Error: test_dump(TestClient::TestGQTP)
  NoMethodError: undefined method `header' for nil:NilClass
test/test-client.rb:85:in `assert_response'
test/test-client.rb:112:in `test_dump'
===============================================================================
E
===============================================================================
Error: test_integer(TestClient::TestGQTP)
  NoMethodError: undefined method `header' for nil:NilClass
test/test-client.rb:92:in `assert_response'
test/test-client.rb:212:in `test_integer'
===============================================================================
E
===============================================================================
Error: test_not_exist(TestClient::TestGQTP)
  NoMethodError: undefined method `header' for nil:NilClass
test/test-client.rb:92:in `assert_response'
test/test-client.rb:185:in `test_not_exist'
===============================================================================
E
===============================================================================
Error: test_xml(TestClient::TestGQTP)
  NoMethodError: undefined method `header' for nil:NilClass
test/test-client.rb:92:in `assert_response'
test/test-client.rb:164:in `test_xml'